### ISSUE TITLE
How use Session and Application?

### ISSUE THREAD

**Issue by Sweet-Bob** [fabfuel/prophiler#30]
How i understood you don't give something sources to repo?
On demo page on timeline, we see Application and Session Component.

I write new Class in Plugin\Phalcon\Mvc\ApplicationPlugin.php and implement appropriate method (events). 
It's work fine, but i don't want implement all listeners :) If they exist by default.

Regards.

**Comment by fabfuel** [comment]
Hi

what exactly do you mean with:
> you don't give something sources to repo?

The content on the demo page is just manually created, have a look here:
https://github.com/fabfuel/prophiler/blob/develop/public/demo.php#L63

You have to write/overwrite all event methods which you would like to track. In these then you have to start or stop a Prophiler benchmark. Here is an example:
https://github.com/fabfuel/prophiler/blob/develop/src/Fabfuel/Prophiler/Plugin/Phalcon/Mvc/DispatcherPlugin.php

I hope that helps!

Best
Fabian

**Comment by Sweet-Bob** [comment]
Thank you, simply i not found sources of demopage :+1: 

Regards.

**Comment by Sweet-Bob** [comment]
Thank you, simply i not found sources of demopage :)
