### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by hardlick** [fabfuel/prophiler#33]
i add in my index.php,
at top:

    require_once(APP_PATH.'vendor/autoload.php');
    $profiler = new \Fabfuel\Prophiler\Profiler();

and the bottom:

    $toolbar = new \Fabfuel\Prophiler\Toolbar($profiler);
    $toolbar->addDataCollector(new \Fabfuel\Prophiler\DataCollector\Request());
    echo $toolbar->render();

But fatal error show:

Fatal error: Interface 'Psr\Log\LoggerInterface' not found in /var/www/feedback/vendor/fabfuel/prophiler/src/Fabfuel/Prophiler/Adapter/Psr/Log/Logger.php on line 12
Help?

**Comment by fabfuel** [comment]
That has been fixed - sorry for that!
Please run `composer update` to get the fix.
