### ISSUE TITLE
Hash link should preventDefault

### ISSUE THREAD

**Issue by aambr** [fabfuel/prophiler#40]
Hi, nice work on this toolbar! One thing that bothers me is that switching between tabs changes URL and adds # to it. It should preventDefault()?

**Comment by fabfuel** [comment]
Thanks! You're totally right. Has been fixed in `develop`: https://github.com/fabfuel/prophiler/commit/9371a7758f5d7200ebeaabad323a3cb9798dfd0f

Best
Fabian
