### ISSUE TITLE
PHP 7 not supported?

### ISSUE THREAD

**Issue by xtreamwayz** [fabfuel/prophiler#47]
```
$ composer require fabfuel/prophiler
Using version ^1.5 for fabfuel/prophiler
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fabfuel/prophiler ^1.5 -> satisfiable by fabfuel/prophiler[1.5.0].
    - fabfuel/prophiler 1.5.0 requires php ~5.4 -> your PHP version (7.0.0RC7) or "config.platform.php" value does not satisfy that requirement.
```

**Comment by fabfuel** [comment]
Currently there are tests depending on the Phalcon extension, which is not available for PHP 7, yet.

I created the branch `feature/php7`, which successfully builds on PHP 7.
You can use this as long as Phalcon is not yet available for PHP 7.
```
"require": {
    "fabfuel/prophiler": "dev-feature/php7"
}
```

Best
Fabian

**Comment by shochdoerfer** [comment]
It seems for me that Phalcon is already compatible with PHP 7 (the build requirements mention "PHP 5.5.x/5.6.x/7.0.x development resources"). Any chance to create a new release or is there anything missing?

**Comment by fabfuel** [comment]
I currently have no time to dig into this. 
Would you please try, if it already works with PHP 7?

**Comment by Caffe1neAdd1ct** [comment]
Just tried out on Phalcon 3 and PHP 7.0.11 and the toolbar appears to be working fine with the `dev-feature/php7` branch :+1:

**Comment by shochdoerfer** [comment]
My first tests were also positive but I was able to test just a small portion of Prophiler so far.

**Comment by ruudboon** [comment]
Are there still plans to get this into a release?

**Comment by fabfuel** [comment]
Support for PHP 7.0 and 7.1 will be added in the next version. See #71
