### ISSUE TITLE
null DB Service problem

### ISSUE THREAD

**Issue by TheCodemasterZz** [fabfuel/prophiler#52]
if possible you can check whether  $this->db is set or not
https://github.com/fabfuel/prophiler/blob/develop/src/Fabfuel/Prophiler/Plugin/Manager/Phalcon.php#L46

**Comment by fabfuel** [comment]
You don't have to use the full convenience method `$manager->register()`.

If you do not have the default "db" service, you can just run:
```php
$manager->registerDispatcher();
$manager->registerView();
```

Best
Fabian

**Comment by TheCodemasterZz** [comment]
thank your your answer. What if i have two database which is named as db1 and db2 service ?

**Comment by fabfuel** [comment]
Then you can register them manually:
```php
use Fabfuel\Prophiler\Plugin\Phalcon\Db\AdapterPlugin;

$db1->getEventsManager()->attach('db', AdapterPlugin::getInstance($profiler));
$db2->getEventsManager()->attach('db', AdapterPlugin::getInstance($profiler));
```
