### ISSUE TITLE
Fix probably need for css

### ISSUE THREAD

**Issue by harikt** [fabfuel/prophiler#53]
Hi, 

When queries are logged it is not possible to see the full queries. It would be nice if there is a way to see the queries that are big. See screenshot .

![screenshot from 2016-01-15 23-06-03](https://cloud.githubusercontent.com/assets/120454/12360247/dbb904aa-bbdc-11e5-8f00-de33510c219d.png)

See the 3rd one looks truncated due to styling issue.

**Comment by harikt** [comment]
Probably it will be good to have the log message in toggle window so it is visible. What do you think ?

**Comment by fabfuel** [comment]
Hi, you can add the query to the $context array, than it will be fully visible in the toggled details area:
https://github.com/fabfuel/prophiler/blob/develop/src/Fabfuel/Prophiler/Adapter/Psr/Log/Logger.php#L130

**Comment by fabfuel** [comment]
This is also how the the other DB loggers (like doctrine) handle it:
https://github.com/fabfuel/prophiler/blob/develop/src/Fabfuel/Prophiler/Adapter/Doctrine/SQLLogger.php#L28-L35

**Comment by harikt** [comment]
Hi @fabfuel ,
Thank you for the information provided.  Currently I am doing 

```php
Log::config('db', function () use ($profiler) {
  $log = new Logger($profiler);
  return $log;
});
```

the same with the method as I mentioned http://harikt.com/blog/2016/01/16/cakephp-orm-and-logging-queries/ 

You can see currently I have no control of it. I will try to find is there is any other way for it to achieve.

**Comment by fabfuel** [comment]
Ah, I see. Maybe you can write your own adapter and write the actual log message to the $context array instead or additionally.

You can extend the Logger adapter, you just have to overwrite the `log()` method:
https://github.com/fabfuel/prophiler/blob/develop/src/Fabfuel/Prophiler/Adapter/Psr/Log/Logger.php#L144-L149

Best
Fabian

**Comment by harikt** [comment]
Thank you, that was a good suggestion :).
