### ISSUE TITLE
PSR Logger Interface cannot be found

### ISSUE THREAD

**Issue by andrewtheone** [fabfuel/prophiler#56]
I just came across with this issue, any idea?

Fatal error: Interface 'Psr\Log\LoggerInterface' not found in /var/www/clients/client2/web4/web/app/services/Fabfuel/Prophiler/Adapter/Psr/Log/Logger.php on line 12

**Comment by fabfuel** [comment]
It's defined as dependency. Did you run `composer install`?

**Comment by fabfuel** [comment]
Closing this for now
