### ISSUE TITLE
Is it possible to see an array detail in log

### ISSUE THREAD

**Issue by Merrick28** [fabfuel/prophiler#82]
Hello,

I would like to debug the content of an array.
I tried
```
$logger->debug($my_array);
```
But all I can see is "array". If I add print_r, nothing is readable anymore.
Is there a way ?

Cheers

**Comment by fagci** [comment]
Docs said about context as 2nd parameter. That is what you need?
Also, you can use json_encode() with pretty print as option.

**Comment by Merrick28** [comment]
It works if I use print_r($myarray,true), so I guess we can close.

**Comment by fabfuel** [comment]
Hi,

the first parameter is a message (= a string). If you want to visualize an array, you can pass it as second parameter `context` as @fagcinsk mentioned:
https://github.com/fabfuel/prophiler/blob/9eba488d343d595ab8856aa56c0c8d8e7bce8994/src/Fabfuel/Prophiler/Adapter/Psr/Log/Logger.php#L123-L134

Here is an example:
https://github.com/fabfuel/prophiler-demo/blob/develop/public/demo.php#L139
(shown here https://prophiler.fabfuel.de/demo.php)

Hint: 
The output is more human readable if you have the xdebug extension enabled.

Best,
Fabian
